site_name: ML Notebook
site_url: https://meyerv11045.github.com/machine-learning
docs_dir: notes

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True

nav:
  - Home: 'index.md'
  - Machine Learning:
    - 'Supervised Learning': 'machine_learning/supervised_learning.md'
    - 'Regression': 'machine_learning/regression.md'
    - 'Classification': 'machine_learning/classification.md'
    - 'Dimensionality Reduction': 'machine_learning/dim_red.md'
    - 'Clustering': 'machine_learning/clustering.md'
    - 'Optimization Techniques': 'machine_learning/optimization.md'
    - 'Feature Scaling': 'machine_learning/feature_scaling.md'
    - 'Model Selection': 'machine_learning/model_selection.md'
    - 'Regularization': 'machine_learning/regularization.md'
    - 'PCA': 'machine_learning/pca.md'
    - 'SVMs': 'machine_learning/svms.md' 
    - 'Reinforcement Learning': 'machine_learning/reinforcement_learning.md'
  - Neural Networks:
    - 'Activation Functions': 'machine_learning/nn/activation_functions.md'
    - 'PyTorch': 'machine_learning/nn/pytorch.md'
    - 'AutoEncoders': 'machine_learning/nn/auto_encoders.md'  
    - 'Self-Supervised Learning': 'machine_learning/nn/ssl.md'
  - Optimization:
    - 'Overview': 'optimization/overview.md'
    - 'Convergence': 'optimization/convergence.md'
    - Root Finding methods:
      - 'Newtons Method': 'optimization/root-methods/newtons.md'
      - 'Secant Method': 'optimization/root-methods/secant.md'
      - 'Bisection': 'optimization/root-methods/bisection.md'
      - 'Regula Falsi': 'optimization/root-methods/regula_falsi.md'
    - 'Model Predictive Control': 'optimization/mpc.md'